daemon: false
log:
    displayLevel: 1
    fileLevel: 1
    filePath: /var/log/centrunk
    activityFilePath: /var/log/centrunk
    fileRoot: DVM-CONV1
network:
    enable: true
    id: xNODE-IDx
    address: 10.147.17.245
    port: 63030
    jitter: 360
    password: "Centrunk!"
    slot1: true
    slot2: true
    updateLookups: false
    allowActivityTransfer: true
    allowDiagnosticTransfer: true
    debug: false
    restEnable: true
    restAddress: xZT-IPx
    restPort: 9991
    restPassword: "Centrunk!"
    restDebug: false
protocols:
    p25:
        enable: true
        tduPreambleCount: 6
        control:
            enable: false
            ackRequests: true
            dedicated: false
            broadcast: false
            interval: 300
            duration: 1
            disableTSDUMBF: false
            enableTimeDateAnn: true
        voiceOnControl: true
        disableCompositeFlag: false
        inhibitUnauthorized: false
        legacyGroupGrnt: true
        legacyGroupReg: false
        verifyAff: false
        verifyReg: false
        dumpDataPacket: false
        repeatDataPacket: true
        dumpTsbkData: false
        callHang: 5
        noStatusAck: false
        noMessageAck: true
        unitToUnitAvailCheck: true
        localEmergAlarm: true
        sndcpGrant: false
        silenceThreshold: 124
        disableNetworkHDU: false
        emergDisabled: true
        queueSize: 15
        verbose: true
        debug: false
system:
    identity: xIDENTITYx
    timeout: 180
    duplex: true
    simplexSameFrequency: false
    modeHang: 1
    fixedMode: true
    rfTalkgroupHang: 10
    activeTickDelay: 5
    idleTickDelay: 5
    localTimeOffset: -6
    info:
        latitude: 30.299419 
        longitude: -97.691909
        height: 30
        power: 1
        location: "Texas, USA"
    config:
        authoritative: true
        supervisor: true
        channelId: 3
        channelNo: 910
        controlCh:
            restAddress: xCC-ZT-IPx
            restPort: 9991
            restPassword: "Centrunk!"
            notifyEnable: false
        voiceChNo:
            - channelNo: 910
              restAddress: xZT-IPx
              restPort: 9991
              restPassword: "Centrunk!"
        nac: xNACx
        ran: 1
        pSuperGroup: 0911
        announcementGroup: 0911
        netId: DEE00
        sysId: 13B
        rfssId: 1
        siteId: xSITEx
    modem:
        protocol:
            type: "uart"
            uart:
                port: /dev/ttyAMA0
                speed: 115200
        rxInvert: false
        txInvert: false
        pttInvert: false
        dcBlocker: true
        cosLockout: false
        fdmaPreamble: 170
        p25CorrCount: 8
        p25FifoLength: 442
        hotspot:
            p25DiscBWAdj: 0
            p25PostBWAdj: 0
            adfGainMode: 0
            afcEnable: false
            afcKI: 11
            afcKP: 4
            afcRange: 1
            txTuning: 0
            rxTuning: 0
        repeater:
            p25SymLvl3Adj: 0
            p25SymLvl1Adj: 0
        softpot:
            rxCoarse: 127
            rxFine: 127
            txCoarse: 127
            txFine: 127
            rssiCoarse: 127
            rssiFine: 127
        rxDCOffset: 0
        txDCOffset: 0
        rxLevel: 50
        txLevel: 50
        rssiMappingFile: RSSI.dat
        packetPlayoutTime: 10
        disableOFlowReset: false
        ignoreModemConfigArea: false
        dumpModemStatus: false
        trace: false
        debug: false
    cwId:
        enable: true
        time: 15
        callsign: WRUP970
    iden_table:
        file: /opt/centrunk/configs/iden_table.dat
        time: 30
    radio_id:
        file: /opt/centrunk/configs/rid_acl.dat
        time: 2
        acl: true
    talkgroup_id:
        file: /opt/centrunk/configs/tg_acl.yml
        time: 2
        acl: true
